# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- bash: echo This script could use $SYSTEM_ACCESSTOKEN
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: './Pipeline2AzureWorkItems.py'
    arguments: '-o oscarrodriguezarias -p Pipeline2AzureWorkItems -t task -token $(System.AccessToken) -f ./results.json'
